Add stevedore to manage datastore adapters
internap/arsenal pull request #54
Opened 2016-10-05 17:17 UTC by lindycoder

To simplify the addition of extra drivers, there is now a datastore config
in the DEFAULT scope

As a bonus. also added py35

2016-10-05 17:29 UTC, mat128 requested changes
.travis.yml should be changed to add 3.5. Also, additional care needs to be taken so only one of the builds releases. Check virtualpdu for the config.

2016-10-05 17:44 UTC, lindycoder commented
py35 removed from this PR

2016-10-06 21:35 UTC, fbouliane approved these changes

2016-10-07 01:02 UTC, mat128 approved these changes

2016-10-07 01:02 UTC, merged